services:
  dns:
    build:
      context: .
      args:
        HOST_IP: ${HOST_IP:-127.0.0.1}
        TLD: ${TLD:-test}
    container_name: launchpad-dns
    network_mode: host
    restart: unless-stopped
